name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Packages and build
        run: |
          npm install

      - name: Build with Parcel
        run: |
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: parcel artifacts
          path: public/
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/download-artifact@master
        with:
          name: parcel artifacts
          path: public/
      - name: Install Packages
        run: |
          npm install
      - name: Run Tests
        run: |
          npm test
        env:
          CI: true
